additional-dependency-files:
  - path: WebApp/khaneliman/package.json
    type: npm-package-json
  - path: WebApp/WebApp.csproj
    type: dotnet-csharp-project
  - path: WebApi/WebApi.csproj
    type: dotnet-csharp-project

ignore-failures:
  csharp:
    - Microsoft.VisualStudio.Azure.Containers.Tools.Targets
  javascript:
    - karma-chrome-launcher 
    - karma-junit-reporter