version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ci

  - package-ecosystem: bun
    directory: /WebApp
    schedule:
      interval: daily
    commit-message:
      prefix: deps(webapp)

  - package-ecosystem: nuget
    directory: /WebApi
    schedule:
      interval: daily
    commit-message:
      prefix: deps(webapi)

  - package-ecosystem: dotnet-sdk
    directory: /WebApi
    schedule:
      interval: daily
    commit-message:
      prefix: deps(dotnet)

  - package-ecosystem: docker
    directory: /WebApp
    schedule:
      interval: daily
    commit-message:
      prefix: deps(webapp-image)

  - package-ecosystem: docker
    directory: /WebApi
    schedule:
      interval: daily
    commit-message:
      prefix: deps(webapi-image)
