services:
  webapi:
    image: khaneliman/austin-horstman-webapi
    build:
      context: ./WebApi
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"

  webapp:
    image: khaneliman/austin-horstman-webapp
    build:
      context: ./WebApp
      dockerfile: Dockerfile.production  # Use production Dockerfile
    ports:
      - "80:80"
    depends_on:
      - webapi