services:
  webapi:
    image: khaneliman/austin-horstman-webapi
    build:
      context: ./WebApi
      dockerfile: Dockerfile
  webapp:
    image: khaneliman/austin-horstman-webapp
    build:
      context: ./WebApp
      dockerfile: Dockerfile
    ports:
      - 4200:4200
