// This file is generated by .github/scripts/update-github-metrics.mjs
// and should be updated via the GitHub Action.

export interface RepoContributionMetrics {
  repo: string;
  mergedPrs: number;
}

export interface GitHubMetrics {
  asOf: string;
  totalMergedPrs: number;
  repoMetrics: RepoContributionMetrics[];
}

export const GITHUB_METRICS: GitHubMetrics = {
  asOf: '2026-08-31',
  totalMergedPrs: 1628,
  repoMetrics: [
    { repo: 'Nixpkgs', mergedPrs: 843 },
    { repo: 'Home Manager', mergedPrs: 470 },
    { repo: 'Nixvim', mergedPrs: 261 },
    { repo: 'Waybar', mergedPrs: 54 },
  ],
};
