// This file is generated by .github/scripts/update-github-metrics.mjs
// and should be updated via the GitHub Action.

export interface RepoContributionMetrics {
  repo: string;
  mergedPrs: number;
}

export interface GitHubMetrics {
  asOf: string;
  totalMergedPrs: number;
  repoMetrics: RepoContributionMetrics[];
}

export const GITHUB_METRICS: GitHubMetrics = {
  asOf: '2026-10-05',
  totalMergedPrs: 1714,
  repoMetrics: [
    { repo: 'Nixpkgs', mergedPrs: 877 },
    { repo: 'Home Manager', mergedPrs: 519 },
    { repo: 'Nixvim', mergedPrs: 263 },
    { repo: 'Waybar', mergedPrs: 55 },
  ],
};
