name: Angular WebApp Build
on:
  push:
    branches: [master]
    paths:
      - 'WebApp/**/*'
  pull_request:
    branches: [master]
    paths:
      - 'WebApp/**/*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch or commit to build'
        required: true
        default: 'master'
      node:
        description: 'Node version to build'
        required: true
        default: '22.x'
jobs:
  build-web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["${{github.event.inputs.node}}"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version || '22.X' }}
          cache: 'npm'
          cache-dependency-path: WebApp/package-lock.json
      - name: Install Dependencies
        working-directory: ./WebApp
        run: npm run ci:install
      - name: Run Full CI Pipeline
        working-directory: ./WebApp
        run: npm run ci:full
