name: Angular WebApp Build
on:
  push:
    branches: [master]
    paths:
      - 'WebApp/**/*'
  pull_request:
    branches: [master]
    paths:
      - 'WebApp/**/*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch or commit to build'
        required: true
        default: 'master'
jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun runtime
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        working-directory: ./WebApp
        run: bun install --frozen-lockfile
      - name: Run Full CI Pipeline
        working-directory: ./WebApp
        run: bun run ci:full
